### PR TITLE
Upgrade dependencies and docs for new Action

### PR DESCRIPTION
**Pull request by aslafy-z**
- Pinned Docker base image version (use [`Renovate`](https://github.com/apps/renovate) to upgrade automatically) 
- Gitleaks: Disable old `--exclude-forks` option
- Gitleaks: config file should be implicitly declared or `--repo-config` added with extra args
- Example with new Action notation 
- Add basic settings:
  - GITLEAKS_REPO
  - GITLEAKS_CONFIG
  - GITLEAKS_EXTRA_ARGS

### CODE REVIEW

**Comment by jbcpollak** [comment]
LGTM

**Comment by jbcpollak** [comment]
Hum... I'm trying to run this branch:

```
name: Git Leaks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: aslafy-z/gitleaks-action@b69f33a989006a03cf2a823737d3517abc3c61fb
```

and I get this output:

```
Run aslafy-z/gitleaks-action@b69f33a989006a03cf2a823737d3517abc3c61fb
/usr/bin/docker run --name dfba6443346da47456f86844c8f3dd1cc86_068f1b --label 488dfb --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/repo/repo":"/github/workspace" 488dfb:a6443346da47456f86844c8f3dd1cc86
ERRO[2020-01-17T22:05:02Z] repository does not exist                    
##[error]Docker run failed with exit code 2
```

any idea what I'm doing wrong?

**Comment by aslafy-z** [comment]
I'm not sure what goes wrong. Can you try with that commit 912885daeb05efa7be94b62b295315cfbb4fad7c. I cannot find where you got the ref you used. I just fixed the default behavior (do not use `--repo-config` if no config is given because it fails it no file exists). See https://github.com/zricethezav/gitleaks/issues/248. 

It works at my side: https://github.com/aslafy-z/gitleaks-action/commit/b50077c650b147913a95ae15de41f95f63504496/checks?check_suite_id=407358253

**Comment by eshork** [comment]
I'm glad that a few others found this quick project was useful.
However, I'm closing down this repo because the gitleaks project now publishes their own github action to wrap the tool.
I highly recommend you switch to that instead. You can find it at: https://github.com/marketplace/actions/gitleaks

**Pull request closed without merging**
